### ISSUE TITLE
Composer config for http-basic 

### ISSUE THREAD

**Issue by rreynier** [ramsey/composer-install#182]
I am trying to install Laravel Nova in my CI workflow. Nova requires authentication. The easiest way which I did in the past when I manually installed Composer (without this action) was to simply run:

```
composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
```

Can this be done with this action? Looks like maybe not at least out of the box.

**Comment by ramsey** [comment]
I'm not sure this should be a concern of this action.

Try out something like this, and let me know if it works for you:

```yaml
- name: "Configure Composer"
  run: |
    composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
- uses: "ramsey/composer-install@v2"
```
