### ISSUE TITLE
failed to open stream 

### ISSUE THREAD

**Issue by ghost** [ramsey/composer-install#223]
Hello, good morning, I created an yml file like this using the examples on the main page.

```yaml
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'public/**'
      - 'laradock/**'
name: 🚀 Deploy website on push (Master)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
      - uses: "ramsey/composer-install@v2"
          
      - name: Config ENV file
        run: mv .env.example .env

      - name: php artisan storage:link
        run: php artisan storage:link

      - name: php artisan optimize:clear
        run: php artisan optimize:clear

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.example.ir
          username: example
          password: ${{ secrets.ftp_password }}
          server-dir: /dev.otoolbox.ir/
```

This action of mine runs correctly, but when I go to the host, an error file is created that shows the error related to the compressor. I manually transferred this folder from local to host and found that it works properly when I add local contents, but it gets an error when dependencies are created automatically.
Thanks to me, help me fix this problem.
