### ISSUE TITLE
`COMPOSER` env variable is ignored since 3.1

### ISSUE THREAD

**Issue by derrabus** [ramsey/composer-install#264]
## Description
Since the 3.1.0 release of the action, our workflow that uses an alternative composer.json file is failing. My guess is that the introduction of the feature #261 is resposible for this.

Since the action did not expose a way to set an alternative composer.json file, we've set the `COMPOSER` environment variable which had the same effect. Apparently, this does not work anymore.

## Steps to reproduce

Use this configuration to install dependencies from a composer.json file called `composer.old.json`:

```yaml
- name: Install dependencies with Composer
  uses: "ramsey/composer-install@v3"
  env:
    COMPOSER: composer.old.json
```

## Expected behavior
Dependencies are read from `composer.old.json`. This used to work prior to the 3.1.0 release.

## Screenshots or output
Composer installs the dependencies from our default `composer.json` file.

## Environment details

- version of this package: 3.1.0
- PHP version: 5.6.40, 8.4.4
- OS: Ubuntu 22.04 (GitHub's runner)

## Additional context
Apparently, the code introduced in #261 always sets the `COMPOSER` env var, even if the new feature is not used. My proposal would be to not touch the `COMPOSER` env var unless the new `composer-filename` option is explicitly set.

**Comment by derrabus** [comment]
Update: I have migrated the project where this change caused trouble to the new `composer-filename` option and it works like a charm. This kind of solves the issue for me.

#### Before
```YAML
- name: Install dependencies with Composer
  uses: "ramsey/composer-install@v3"
  env:
    COMPOSER: composer.old.json
```

#### After
```YAML
- name: Install dependencies with Composer
  uses: "ramsey/composer-install@v3"
  with:
    composer-filename: composer.old
```

Still, I believe allowing the "old" way alongside the new one would not hurt and create a smoother upgrade experience for everyone.
