### ISSUE TITLE
Build failing when composer no longer has accessed to checksum data

### ISSUE THREAD

**Issue by crynobone** [ramsey/composer-install#47]
![image](https://user-images.githubusercontent.com/172966/97989216-2f35c200-1e19-11eb-8e94-762582843ea2.png)

See https://github.com/orchestral/testbench-core/actions/runs/343623322

Workflow:

```yaml
name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
        php:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        dependencies:
          - "locked"
          - "lowest"
          - "highest"
        experimental:
          - false

    name: PHP${{ matrix.php }} on ${{ matrix.os }} (${{ matrix.dependencies }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
      - name: Execute tests
        run: vendor/bin/phpunit
```

**Comment by ramsey** [comment]
Does it fail consistently, or is it intermittent?

**Comment by crynobone** [comment]
Once it failed, it fail consistently. tried using `composer-options: "--prefer-dist"` but seem to experience similar issue (with zip) this time.

https://github.com/orchestral/testbench-core/runs/1347871674

**Comment by crynobone** [comment]
Able to avoid the issue by using the following options:

```yaml
- uses: "ramsey/composer-install@v1"
  with:
    composer-options: "--prefer-dist --no-cache"
```
