### ISSUE TITLE
Action will not work if composer.json is located in a sub dir

### ISSUE THREAD

**Issue by OskarStark** [ramsey/composer-install#58]
Hi, thanks for this amazing tool 👍 

This is my project strucure in short:
```
.github/workflows/ci.yaml
...
backend/composer.json
...
frontend/package.json
...
```

I tried using (`working-directory`, this is what other action use):
```yaml
            -
                name: "Composer install"
                uses: "ramsey/composer-install@v1"
                working-directory: "backend"
                with:
                    composer-options: "--no-scripts"
```

and:

```yaml
            -
                name: "Composer install"
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "--no-scripts --working-dir=backend"
```

but this does not work 🤔  I don't have that much info:
![CleanShot 2020-11-17 at 08 05 48](https://user-images.githubusercontent.com/995707/99357180-c552f900-28ab-11eb-8916-4af64087559a.png)

Thank you!

cc @localheinz
