### ISSUE TITLE
Local run action using act fails, but on the repo it passes

### ISSUE THREAD

**Issue by dingo-d** [ramsey/composer-install#66]
Hi!

I noticed that when I run my actions using [act](https://github.com/nektos/act), the composer dependency installation fails

<details>
<summary>Local setup</summary>
<pre><code>
[CS/Quality control checks] 🚀  Start image=shivammathur/node:latest
[CS/Quality control checks]   🐳  docker run image=shivammathur/node:latest entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[CS/Quality control checks]   🐳  docker cp src=/Users/denis.zoljom/Projects/Personal/wpthemeReview/. dst=/github/workspace
[CS/Quality control checks] ⭐  Run Checkout
[CS/Quality control checks]   ✅  Success - Checkout
[CS/Quality control checks] ⭐  Run PHP setup
[CS/Quality control checks]   ☁  git clone 'https://github.com/shivammathur/setup-php' # ref=v2
[CS/Quality control checks]   🐳  docker cp src=/Users/denis.zoljom/.cache/act/shivammathur-setup-php@v2 dst=/actions/
| [command]/bin/bash /opt/hostedtoolcache/linux.sh 7.4 /actions/shivammathur-setup-php@v2/dist
|
| ==> Setup PHP
| ✓ PHP Switched to PHP 7.4.13
|
| ==> Setup Tools
| ✓ composer Added composer 2.0.8
|
| ==> Setup Coverage
| ✓ none Disabled Xdebug and PCOV
|
| ==> Support this project
| ✓ setup-php https://setup-php.com/support
[CS/Quality control checks]   ✅  Success - PHP setup
[CS/Quality control checks] ⭐  Run Set the required PHPCS and WPCS versions
| ./composer.json has been updated
[CS/Quality control checks]   ✅  Success - Set the required PHPCS and WPCS versions
[CS/Quality control checks] ⭐  Run Install Composer dependencies
[CS/Quality control checks]   ☁  git clone 'https://github.com/ramsey/composer-install' # ref=v1
[CS/Quality control checks]   🐳  docker cp src=/Users/denis.zoljom/.cache/act/ramsey-composer-install@v1 dst=/actions/
| Composer cache directory found at /github/home/.composer/cache
| Using locked versions of dependencies
[CS/Quality control checks]   💬  ::debug::followSymbolicLinks 'false'
[CS/Quality control checks]   💬  ::debug::followSymbolicLinks 'false'
[CS/Quality control checks]   💬  ::debug::implicitDescendants 'true'
[CS/Quality control checks]   💬  ::debug::omitBrokenSymbolicLinks 'true'
[CS/Quality control checks]   💬  ::debug::Search path '/github/workspace/composer.json'
[CS/Quality control checks]   💬  ::debug::Search path '/github/workspace/composer.lock'
| PHP version is 7.4.13
| Cache primary key is php-7.4.13-locked-974c02999424f7583279b267a29d3e00a005175094444241082724389aa09653-
| Cache restore keys are: php-7.4.13-locked-974c02999424f7583279b267a29d3e00a005175094444241082724389aa09653-, php-7.4.13-locked-
[CS/Quality control checks]   ❓  ::save-state name=CACHE_KEY::php-7.4.13-locked-974c02999424f7583279b267a29d3e00a005175094444241082724389aa09653-
[CS/Quality control checks]   💬  ::debug::Resolved Keys:
[CS/Quality control checks]   💬  ::debug::["php-7.4.13-locked-974c02999424f7583279b267a29d3e00a005175094444241082724389aa09653-","php-7.4.13-locked-974c02999424f7583279b267a29d3e00a005175094444241082724389aa09653-","php-7.4.13-locked-"]
[CS/Quality control checks]   💬  ::debug::Checking zstd --version
| [command]/usr/local/bin/composer install --no-interaction --no-progress --ansi
[CS/Quality control checks]   💬  ::debug::Unable to locate executable file: zstd. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
[CS/Quality control checks]   💬  ::debug::
[CS/Quality control checks]   💬  ::debug::getCacheEntry - Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[CS/Quality control checks]   💬  ::debug::getCacheEntry - Attempt 2 of 2 failed with error: Cache Service Url not found, unable to restore cache.
| [warning]getCacheEntry failed: Cache Service Url not found, unable to restore cache.
[CS/Quality control checks]   ⚙  ::set-output:: cache-hit=false
| No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
| Loading composer repositories with package information
| Updating dependencies
| Lock file operations: 36 installs, 0 updates, 0 removals
|   - Locking dealerdirect/phpcodesniffer-composer-installer (v0.7.1)
|   - Locking doctrine/instantiator (1.4.0)
|   - Locking myclabs/deep-copy (1.10.2)
|   - Locking phar-io/manifest (1.0.3)
|   - Locking phar-io/version (2.0.1)
|   - Locking phpcompatibility/php-compatibility (9.3.5)
|   - Locking phpcompatibility/phpcompatibility-paragonie (1.3.0)
|   - Locking phpcompatibility/phpcompatibility-wp (2.1.0)
|   - Locking phpcsstandards/phpcsdevtools (1.0.1)
|   - Locking phpdocumentor/reflection-common (2.2.0)
|   - Locking phpdocumentor/reflection-docblock (5.2.2)
|   - Locking phpdocumentor/type-resolver (1.4.0)
|   - Locking phpspec/prophecy (1.12.2)
|   - Locking phpunit/php-code-coverage (6.1.4)
|   - Locking phpunit/php-file-iterator (2.0.3)
|   - Locking phpunit/php-text-template (1.2.1)
|   - Locking phpunit/php-timer (2.1.3)
|   - Locking phpunit/php-token-stream (3.1.2)
|   - Locking phpunit/phpunit (7.5.20)
|   - Locking roave/security-advisories (dev-master d596191)
|   - Locking sebastian/code-unit-reverse-lookup (1.0.2)
|   - Locking sebastian/comparator (3.0.3)
|   - Locking sebastian/diff (3.0.3)
|   - Locking sebastian/environment (4.2.4)
|   - Locking sebastian/exporter (3.1.3)
|   - Locking sebastian/global-state (2.0.0)
|   - Locking sebastian/object-enumerator (3.0.4)
|   - Locking sebastian/object-reflector (1.1.2)
|   - Locking sebastian/recursion-context (3.0.1)
|   - Locking sebastian/resource-operations (2.0.2)
|   - Locking sebastian/version (2.0.1)
|   - Locking squizlabs/php_codesniffer (dev-master 9bcb29c)
|   - Locking symfony/polyfill-ctype (v1.20.0)
|   - Locking theseer/tokenizer (1.2.0)
|   - Locking webmozart/assert (1.9.1)
|   - Locking wp-coding-standards/wpcs (dev-master 7da1894)
| Writing lock file
| Installing dependencies from lock file (including require-dev)
| Package operations: 36 installs, 0 updates, 0 removals
|   - Downloading dealerdirect/phpcodesniffer-composer-installer (v0.7.1)
|   - Downloading phpcompatibility/php-compatibility (9.3.5)
|   - Downloading phpcompatibility/phpcompatibility-paragonie (1.3.0)
|   - Downloading phpcompatibility/phpcompatibility-wp (2.1.0)
|   - Downloading phpcsstandards/phpcsdevtools (1.0.1)
|   - Downloading symfony/polyfill-ctype (v1.20.0)
|   - Downloading webmozart/assert (1.9.1)
|   - Downloading phpdocumentor/reflection-common (2.2.0)
|   - Downloading phpdocumentor/type-resolver (1.4.0)
|   - Downloading phpdocumentor/reflection-docblock (5.2.2)
|   - Downloading phpunit/php-token-stream (3.1.2)
|   - Downloading sebastian/version (2.0.1)
|   - Downloading sebastian/resource-operations (2.0.2)
|   - Downloading sebastian/recursion-context (3.0.1)
|   - Downloading sebastian/object-reflector (1.1.2)
|   - Downloading sebastian/object-enumerator (3.0.4)
|   - Downloading sebastian/global-state (2.0.0)
|   - Downloading sebastian/exporter (3.1.3)
|   - Downloading sebastian/environment (4.2.4)
|   - Downloading sebastian/diff (3.0.3)
|   - Downloading sebastian/comparator (3.0.3)
|   - Downloading phpunit/php-timer (2.1.3)
|   - Downloading phpunit/php-text-template (1.2.1)
|   - Downloading phpunit/php-file-iterator (2.0.3)
|   - Downloading theseer/tokenizer (1.2.0)
|   - Downloading sebastian/code-unit-reverse-lookup (1.0.2)
|   - Downloading phpunit/php-code-coverage (6.1.4)
|   - Downloading doctrine/instantiator (1.4.0)
|   - Downloading phpspec/prophecy (1.12.2)
|   - Downloading phar-io/version (2.0.1)
|   - Downloading phar-io/manifest (1.0.3)
|   - Downloading myclabs/deep-copy (1.10.2)
|   - Downloading phpunit/phpunit (7.5.20)
|   - Installing squizlabs/php_codesniffer (dev-master 9bcb29c): Cloning 9bcb29cce8
|     Install of squizlabs/php_codesniffer failed
| ::error ::Failed to clone https://github.com/squizlabs/PHP_CodeSniffer.git, git was not found, check that it is installed and in your PATH env.%0A%0Ash: 1: git: not found%0A
|
|
|   [RuntimeException]
|   Failed to clone https://github.com/squizlabs/PHP_CodeSniffer.git, git was not found, check that it is installed and in your PATH env.
|
|   sh: 1: git: not found
|
|
| install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...
|
[CS/Quality control checks]   ❗  ::error::The process '/usr/local/bin/composer' failed with exit code 1
[CS/Quality control checks]   ❌  Failure - Install Composer dependencies
Error: exit with `FAILURE`: 1
</code>
</pre>
</details>

This is odd since the setup is passing on the actual repo: https://github.com/WPTT/WPThemeReview/pull/261/checks?check_run_id=1584111259

Any ideas what could be the issue?

This is the workflow file

```yaml
name: CS

on:
  # Run on PRs and pushes, only on significant changes.
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  XMLLINT_INDENT: '	'

jobs:
    qa_checks:
        name: Quality control checks
        runs-on: ubuntu-latest

        steps:
            # Checkout repository
            - name: Checkout
              uses: actions/checkout@v2

            # Setup PHP versions, run checks
            - name: PHP setup
              uses: shivammathur/setup-php@v2
              with:
                php-version: '7.4'
                coverage: none
              env:
                COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Set the required PHPCS and WPCS versions
              run: composer require squizlabs/php_codesniffer:"dev-master" wp-coding-standards/wpcs:"dev-master" --no-update --no-scripts

            # Install dependencies and handle caching in one go.
            # @link https://github.com/marketplace/actions/install-composer-dependencies
            - name: Install Composer dependencies
              uses: "ramsey/composer-install@v1"

            - name: Install xmllint
              run: sudo apt-get install --no-install-recommends -y libxml2-utils

            # Show XML violations inline in the file diff.
            # @link https://github.com/marketplace/actions/xmllint-problem-matcher
            - uses: korelstar/xmllint-problem-matcher@v1

            - name: Validate ruleset against schema
              run: xmllint --noout --schema ./vendor/squizlabs/php_codesniffer/phpcs.xsd ./*/ruleset.xml

            - name: Check the code-style consistency of the xml files.
              run: diff -B --tabsize=4 ./WPThemeReview/ruleset.xml <(xmllint --format "./WPThemeReview/ruleset.xml")

            - name: Lint the PHP files against parse errors
              run: if find . -path ./vendor -prune -o -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi

            - name: Validate the composer.json file.
              run: composer validate --no-check-all --strict

            - name: Check the code style of the WPThemeReview codebase
              run: composer check-cs

            - name: Check feature completeness of the available sniffs
              run: composer check-complete
```

I tried deleting all my docker images, doing `docker system prune`, nothing helped.

I am running this on MacOS 11.1 (Big Sur)
Docker version: Docker version 20.10.0, build 7287ab3 and Docker desktop 3.0.1
