### ISSUE TITLE
Allow input for php executable

### ISSUE THREAD

**Issue by pkruithof** [ramsey/composer-install#75]
Not sure if this is even possible or in scope for this action, but we install dependencies inside a Docker container where we also have our required extensions available. We can't use this action with that unfortunately. I think that if you're able to set the php/composer executable that this could work something like this:

```yaml
- uses: "ramsey/composer-install@v1"
  with:
    php: "docker-compose run --rm php"
```

The main reason we do it this way is because some packages install different versions depending on the php environment (like Ocramius/ProxyManager if I remember correctly). We could replicate our environment using `shivammathur/setup-php` of course, but that would mean maintaining our php environment in 2 places.

Is this something you'd consider?
