### ISSUE TITLE
Check fails both locally with act and on the action run on GH

### ISSUE THREAD

**Issue by dingo-d** [ramsey/composer-install#88]
Hi!

My action looks like this:

```yml
name: Continuous integration checks

on:
  # Run on PRs and pushes, only on significant changes.
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  phpcs:
    name: PHPCS check on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - name: Check coding standards using PHPCS
        run: composer standards:check -- --runtime-set testVersion ${{ matrix.php }}-
```

But when I run it I get

```bash
[Continuous integration checks/PHPCS check on PHP 7.4] 🧪  Matrix: map[php:7.4]
[Continuous integration checks/PHPCS check on PHP 7.4] 🚀  Start image=shivammathur/node:latest
[Continuous integration checks/PHPCS check on PHP 7.4]   🐳  docker run image=shivammathur/node:latest entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Continuous integration checks/PHPCS check on PHP 7.4]   🐳  docker cp src=/Users/denis.zoljom/Projects/Infinum/wordpress-ci-cd-test/. dst=/github/workspace
[Continuous integration checks/PHPCS check on PHP 7.4] ⭐  Run Checkout
[Continuous integration checks/PHPCS check on PHP 7.4]   ✅  Success - Checkout
[Continuous integration checks/PHPCS check on PHP 7.4] ⭐  Run PHP setup
[Continuous integration checks/PHPCS check on PHP 7.4]   ☁  git clone 'https://github.com/shivammathur/setup-php' # ref=v2
[Continuous integration checks/PHPCS check on PHP 7.4]   🐳  docker cp src=/Users/denis.zoljom/.cache/act/shivammathur-setup-php@v2 dst=/actions/
| [command]/bin/bash /opt/hostedtoolcache/linux.sh 7.4 /actions/shivammathur-setup-php@v2/dist
|
| ==> Setup PHP
| ✓ PHP Switched to PHP 7.4.13
|
| ==> Setup Tools
| ✓ composer Added composer 1.10.20
| ✓ deployer Added deployer 6.8.0
| ✓ wp-cli Added wp-cli
|
| ==> Setup Coverage
| ✓ none Disabled Xdebug and PCOV
|
| ==> Support this project
| ✓ setup-php https://setup-php.com/support
[Continuous integration checks/PHPCS check on PHP 7.4]   ✅  Success - PHP setup
[Continuous integration checks/PHPCS check on PHP 7.4] ⭐  Run Install Composer dependencies
[Continuous integration checks/PHPCS check on PHP 7.4]   ☁  git clone 'https://github.com/ramsey/composer-install' # ref=v1
[Continuous integration checks/PHPCS check on PHP 7.4]   🐳  docker cp src=/Users/denis.zoljom/.cache/act/ramsey-composer-install@v1 dst=/actions/
[Continuous integration checks/PHPCS check on PHP 7.4]   ❗  ::error::The process '/usr/local/bin/composer' failed with exit code 1
[Continuous integration checks/PHPCS check on PHP 7.4]   ❌  Failure - Install Composer dependencies
Error: exit with `FAILURE`: 1
```

if I run the action with -v flag I get

```bash
[Continuous integration checks/PHPCS check on PHP 7.4] ⭐  Run Install Composer dependencies
[Continuous integration checks/PHPCS check on PHP 7.4]   ☁  git clone 'https://github.com/ramsey/composer-install' # ref=v1
[Continuous integration checks/PHPCS check on PHP 7.4]   cloning https://github.com/ramsey/composer-install to /Users/denis.zoljom/.cache/act/ramsey-composer-install@v1
[Continuous integration checks/PHPCS check on PHP 7.4] Provided ref is not a sha. Checking out branch before pulling changes
[Continuous integration checks/PHPCS check on PHP 7.4] Cloned https://github.com/ramsey/composer-install to /Users/denis.zoljom/.cache/act/ramsey-composer-install@v1
[Continuous integration checks/PHPCS check on PHP 7.4] Checked out v1
DEBU[0022] Read action &{Install Composer Dependencies Ben Ramsey Installs and caches Composer dependencies, accepting arguments to configure how and what to install. map[composer-options:{Additional options to pass to Composer (e.g. --ignore-platform-reqs). false } dependency-versions:{The version of dependencies to prefer (lowest, highest, or locked). true locked}] map[] {node12 map[] dist/main/index.js  [] []} {purple download}} from '/Users/denis.zoljom/.cache/act/ramsey-composer-install@v1/action.yml'
DEBU[0022] About to run action &{Install Composer Dependencies Ben Ramsey Installs and caches Composer dependencies, accepting arguments to configure how and what to install. map[composer-options:{Additional options to pass to Composer (e.g. --ignore-platform-reqs). false } dependency-versions:{The version of dependencies to prefer (lowest, highest, or locked). true locked}] map[] {node12 map[] dist/main/index.js  [] []} {purple download}}
DEBU[0022] type=3 actionDir=/Users/denis.zoljom/.cache/act/ramsey-composer-install@v1 actionPath= Workdir=/Users/denis.zoljom/Projects/Infinum/wordpress-ci-cd-test ActionCacheDir=/Users/denis.zoljom/.cache/act actionName=ramsey-composer-install@v1 containerActionDir=/actions
DEBU[0022] Removing /Users/denis.zoljom/.cache/act/ramsey-composer-install@v1/.gitignore before docker cp
[Continuous integration checks/PHPCS check on PHP 7.4]   🐳  docker cp src=/Users/denis.zoljom/.cache/act/ramsey-composer-install@v1 dst=/actions/
[Continuous integration checks/PHPCS check on PHP 7.4] Exec command '[mkdir -p /actions/]'
DEBU[0022] Writing tarball /var/folders/mf/jxbsh3dd6zb43qy2mw1cgq1r0000gn/T/act008565115 from /Users/denis.zoljom/.cache/act/ramsey-composer-install@v1
DEBU[0022] Stripping prefix:/Users/denis.zoljom/.cache/act/ src:/Users/denis.zoljom/.cache/act/ramsey-composer-install@v1
[Continuous integration checks/PHPCS check on PHP 7.4] Extracting content from '/var/folders/mf/jxbsh3dd6zb43qy2mw1cgq1r0000gn/T/act008565115' to '/actions/'
DEBU[0022] executing remote job container: [node /actions/ramsey-composer-install@v1/dist/main/index.js]
[Continuous integration checks/PHPCS check on PHP 7.4] Exec command '[node /actions/ramsey-composer-install@v1/dist/main/index.js]'
[Continuous integration checks/PHPCS check on PHP 7.4]   ❗  ::error::The process '/usr/local/bin/composer' failed with exit code 1
[Continuous integration checks/PHPCS check on PHP 7.4]   ❌  Failure - Install Composer dependencies
DEBU[0023] exit with `FAILURE`: 1
DEBU[0023] exit with `FAILURE`: 1
Error: exit with `FAILURE`: 1
```

Not sure what seems to be the problem 🤷🏼‍♂️
